Repository fedspendingtransparency/data-act-broker-backend, pull requests merged in 2020-07, with the labels that each got.

#1909 updating datadog trace client
  requirements.txt
Labels: ready for review

#1915 reverting ddtace client upgrade
  requirements.txt
Labels: ready for review

#1917 [DEV-5582] make batch size configurable
  dataactcore/config_example.yml
  dataactcore/local_config_example.yml
  dataactvalidator/validation_handlers/validationManager.py
Labels: in progress

#1926 [HOTFIX] Uploading the Error/Warning files to S3 Better
  dataactvalidator/validation_handlers/validationManager.py
Labels: hotfix

#1922 [HOTFIX][DEV-5600] Optimize CSV data processing with vectorized use of Pandas
  dataactbroker/helpers/validation_helper.py
  dataactcore/models/domainModels.py
  dataactvalidator/config/sqlrules/c8_award_financial.sql
  dataactvalidator/config/sqlrules/c9_award_financial.sql
  dataactvalidator/filestreaming/fieldCleaner.py
  dataactvalidator/scripts/loader_utils.py
  dataactvalidator/validation_handlers/validationManager.py
  docker-compose.frontend.yml
  requirements.txt
  tests/unit/dataactbroker/test_validation_helper.py
Labels: hotfix

#1931 Warmfixes: Write Stream Query Upload and FABS Metadata
  dataactbroker/handlers/submission_handler.py
  dataactvalidator/filestreaming/csv_selection.py
Labels: warmfix

#1929 Flex field Copy fix
  dataactvalidator/validation_handlers/validationManager.py
Labels: warmfix

#1927 Updating crossfile uploading
  dataactvalidator/validation_handlers/validationManager.py
Labels: warmfix

#1930 WARMFIX: DEV-5580 fabs publishing speedup
  dataactbroker/handlers/fileHandler.py
  dataactbroker/helpers/fabs_derivations_helper.py
  dataactcore/migrations/versions/be4dcb9eede6_add_multicolumn_upper_indexes_to_.py
  dataactcore/models/stagingModels.py
  dataactcore/utils/business_categories.py
  tests/unit/dataactbroker/test_fabs_derivations.py
  tests/unit/dataactcore/factories/domain.py
Labels: warmfix
