Repository fedspendingtransparency/data-act-broker-backend, pull requests merged in 2021-01, with the labels that each got.

#2008 DEV-6579: Deactivate A2
  dataactvalidator/config/sqlrules/sqlRules.csv
  tests/integration/error_warning_file_tests.py
Labels: hotfix

#2014 DEV-6630: Submission Comment in comment file
  dataactbroker/handlers/fileHandler.py
  tests/unit/dataactbroker/test_file_handler.py
Labels: ready for review

#2018 Federal Hierarchy Retries
  dataactcore/scripts/load_federal_hierarchy.py
Labels: hotfix, ready for review
